/*[
{
    "symbol": "ORANW-NA",
    "companyName": "Oranjewoud NV",
    "primaryExchange": "Euronext Amsterdam",
    "calculationPrice": "close",
    "open": null,
    "openTime": null,
    "openSource": "official",
    "close": null,
    "closeTime": null,
    "closeSource": "official",
    "high": 6.1,
    "highTime": 1600804800000,
    "highSource": "Close",
    "low": 5.5,
    "lowTime": 1603396800000,
    "lowSource": "Close",
    "latestPrice": 6,
    "latestSource": "Close",
    "latestTime": "November 27, 2020",
    "latestUpdate": 1606510800000,
    "latestVolume": 0,
    "iexRealtimePrice": null,
    "iexRealtimeSize": null,
    "iexLastUpdated": null,
    "delayedPrice": null,
    "delayedPriceTime": null,
    "oddLotDelayedPrice": null,
    "oddLotDelayedPriceTime": null,
    "extendedPrice": null,
    "extendedChange": null,
    "extendedChangePercent": null,
    "extendedPriceTime": null,
    "previousClose": 6,
    "previousVolume": null,
    "change": 0,
    "changePercent": 0,
    "volume": 0,
    "iexMarketPercent": null,
    "iexVolume": null,
    "avgTotalVolume": 1238,
    "iexBidPrice": null,
    "iexBidSize": null,
    "iexAskPrice": null,
    "iexAskSize": null,
    "iexOpen": null,
    "iexOpenTime": null,
    "iexClose": null,
    "iexCloseTime": null,
    "marketCap": 0,
    "peRatio": null,
    "week52High": 6.3,
    "week52Low": 5.5,
    "ytdChange": -0.016393,
    "lastTradeTime": null
},
{
    "symbol": "LTELF",
    "companyName": "LS telcom AG",
    "primaryExchange": "US OTC",
    "calculationPrice": "previousclose",
    "open": null,
    "openTime": null,
    "close": null,
    "closeTime": null,
    "high": null,
    "low": null,
    "latestPrice": null,
    "latestSource": "N/A",
    "latestTime": "N/A",
    "latestUpdate": null,
    "latestVolume": 0,
    "iexRealtimePrice": null,
    "iexRealtimeSize": null,
    "iexLastUpdated": null,
    "delayedPrice": null,
    "delayedPriceTime": null,
    "oddLotDelayedPrice": null,
    "oddLotDelayedPriceTime": null,
    "extendedPrice": null,
    "extendedChange": null,
    "extendedChangePercent": null,
    "extendedPriceTime": null,
    "previousClose": null,
    "previousVolume": null,
    "change": null,
    "changePercent": null,
    "volume": 0,
    "iexMarketPercent": null,
    "iexVolume": null,
    "avgTotalVolume": null,
    "iexBidPrice": null,
    "iexBidSize": null,
    "iexAskPrice": null,
    "iexAskSize": null,
    "marketCap": null,
    "peRatio": null,
    "week52High": 0,
    "week52Low": 0,
    "ytdChange": 0,
    "lastTradeTime": null
},
{
    "symbol": "SSYNF",
    "companyName": "Sensyne Health Plc",
    "primaryExchange": "US OTC",
    "calculationPrice": "close",
    "open": null,
    "openTime": null,
    "openSource": "official",
    "close": null,
    "closeTime": null,
    "closeSource": "official",
    "high": 0.9511,
    "highTime": 1603483200000,
    "highSource": "Close",
    "low": 0.4311,
    "lowTime": 1597262400000,
    "lowSource": "Previous close",
    "latestPrice": 0.9511,
    "latestSource": "Close",
    "latestTime": "October 23, 2020",
    "latestUpdate": 1603483200000,
    "latestVolume": 0,
    "iexRealtimePrice": null,
    "iexRealtimeSize": null,
    "iexLastUpdated": null,
    "delayedPrice": null,
    "delayedPriceTime": null,
    "oddLotDelayedPrice": null,
    "oddLotDelayedPriceTime": null,
    "extendedPrice": null,
    "extendedChange": null,
    "extendedChangePercent": null,
    "extendedPriceTime": null,
    "previousClose": 0.9511,
    "previousVolume": null,
    "change": 0,
    "changePercent": 0,
    "volume": 0,
    "iexMarketPercent": null,
    "iexVolume": null,
    "avgTotalVolume": 0,
    "iexBidPrice": null,
    "iexBidSize": null,
    "iexAskPrice": null,
    "iexAskSize": null,
    "iexOpen": null,
    "iexOpenTime": null,
    "iexClose": null,
    "iexCloseTime": null,
    "marketCap": 122284365,
    "peRatio": null,
    "week52High": 0.9511,
    "week52Low": 0.4311,
    "ytdChange": 1.206217,
    "lastTradeTime": 1599747863996
},
{
    "symbol": "004920-KP",
    "companyName": "CITECH CO., LTD.",
    "primaryExchange": "Korea Exchange",
    "calculationPrice": "close",
    "open": null,
    "openTime": null,
    "openSource": "official",
    "close": null,
    "closeTime": null,
    "closeSource": "official",
    "high": 955,
    "highTime": 1606510800000,
    "highSource": "Close",
    "low": 955,
    "lowTime": 1606510800000,
    "lowSource": "Close",
    "latestPrice": 955,
    "latestSource": "Close",
    "latestTime": "November 27, 2020",
    "latestUpdate": 1606510800000,
    "latestVolume": 0,
    "iexRealtimePrice": null,
    "iexRealtimeSize": null,
    "iexLastUpdated": null,
    "delayedPrice": null,
    "delayedPriceTime": null,
    "oddLotDelayedPrice": null,
    "oddLotDelayedPriceTime": null,
    "extendedPrice": null,
    "extendedChange": null,
    "extendedChangePercent": null,
    "extendedPriceTime": null,
    "previousClose": 946,
    "previousVolume": 49059,
    "change": 9,
    "changePercent": 0.00951,
    "volume": 0,
    "iexMarketPercent": null,
    "iexVolume": null,
    "avgTotalVolume": 179505,
    "iexBidPrice": null,
    "iexBidSize": null,
    "iexAskPrice": null,
    "iexAskSize": null,
    "iexOpen": null,
    "iexOpenTime": null,
    "iexClose": null,
    "iexCloseTime": null,
    "marketCap": 0,
    "peRatio": null,
    "week52High": 1440,
    "week52Low": 510,
    "ytdChange": -0.295439,
    "lastTradeTime": null
},
{
    "symbol": "UBSFY",
    "companyName": "Ubisoft Entertainment SA",
    "primaryExchange": "US OTC",
    "calculationPrice": "close",
    "open": 18.48,
    "openTime": 1606487402283,
    "openSource": "official",
    "close": 18.82,
    "closeTime": 1606504800000,
    "closeSource": "official",
    "high": 18.84,
    "highTime": 1606499100619,
    "highSource": "15 minute delayed price",
    "low": 18.48,
    "lowTime": 1606487402283,
    "lowSource": "15 minute delayed price",
    "latestPrice": 18.82,
    "latestSource": "Close",
    "latestTime": "November 27, 2020",
    "latestUpdate": 1606504800000,
    "latestVolume": 23051,
    "iexRealtimePrice": null,
    "iexRealtimeSize": null,
    "iexLastUpdated": null,
    "delayedPrice": 18.82,
    "delayedPriceTime": 1606499076596,
    "oddLotDelayedPrice": 18.785,
    "oddLotDelayedPriceTime": 1606499859596,
    "extendedPrice": 18.56,
    "extendedChange": -0.26,
    "extendedChangePercent": -0.01382,
    "extendedPriceTime": 1605214800320,
    "previousClose": 18.29,
    "previousVolume": 16690,
    "change": 0.53,
    "changePercent": 0.02898,
    "volume": 23051,
    "iexMarketPercent": null,
    "iexVolume": null,
    "avgTotalVolume": 66508,
    "iexBidPrice": null,
    "iexBidSize": null,
    "iexAskPrice": null,
    "iexAskSize": null,
    "iexOpen": null,
    "iexOpenTime": null,
    "iexClose": null,
    "iexCloseTime": null,
    "marketCap": 11573981942,
    "peRatio": -98.69,
    "week52High": 19.91,
    "week52Low": 11.7,
    "ytdChange": 0.380021,
    "lastTradeTime": 1606499076596
},
{
    "symbol": "MB",
    "companyName": "MINDBODY, Inc. Class A",
    "primaryExchange": "NASDAQ",
    "sector": "Technology Services",
    "calculationPrice": "tops",
    "open": null,
    "openTime": null,
    "close": null,
    "closeTime": null,
    "high": 369200,
    "low": 366000,
    "latestPrice": 36.8,
    "latestSource": "IEX real time price",
    "latestTime": "9:56:26 AM",
    "latestUpdate": 1547736986153,
    "latestVolume": null,
    "iexRealtimePrice": 36.8,
    "iexRealtimeSize": 100,
    "iexLastUpdated": 1547736986153,
    "delayedPrice": 368600,
    "delayedPriceTime": 94455377,
    "extendedPrice": null,
    "extendedChange": null,
    "extendedChangePercent": null,
    "extendedPriceTime": null,
    "previousClose": null,
    "change": null,
    "changePercent": null,
    "iexMarketPercent": null,
    "iexVolume": 2500,
    "avgTotalVolume": 0,
    "iexBidPrice": 36.7,
    "iexBidSize": 100,
    "iexAskPrice": 0,
    "iexAskSize": 0,
    "marketCap": 1727516053,
    "peRatio": null,
    "week52High": 369200,
    "week52Low": 0,
    "ytdChange": 0
},
{
    "symbol": "PTIX",
    "companyName": "Protagenic Therapeutics, Inc.",
    "primaryExchange": "US OTC",
    "calculationPrice": "close",
    "open": null,
    "openTime": null,
    "openSource": "official",
    "close": null,
    "closeTime": null,
    "closeSource": "official",
    "high": 1.05,
    "highTime": 1606510800000,
    "highSource": "Close",
    "low": 1.05,
    "lowTime": 1604597901193,
    "lowSource": "15 minute delayed price",
    "latestPrice": 1.05,
    "latestSource": "Close",
    "latestTime": "November 27, 2020",
    "latestUpdate": 1606510800000,
    "latestVolume": 0,
    "iexRealtimePrice": null,
    "iexRealtimeSize": null,
    "iexLastUpdated": null,
    "delayedPrice": null,
    "delayedPriceTime": null,
    "oddLotDelayedPrice": 1.05,
    "oddLotDelayedPriceTime": 1606318871154,
    "extendedPrice": 1.16,
    "extendedChange": 0.11,
    "extendedChangePercent": 0.10476,
    "extendedPriceTime": 1596225617254,
    "previousClose": 1.05,
    "previousVolume": 1,
    "change": 0,
    "changePercent": 0,
    "volume": 0,
    "iexMarketPercent": null,
    "iexVolume": null,
    "avgTotalVolume": 29,
    "iexBidPrice": null,
    "iexBidSize": null,
    "iexAskPrice": null,
    "iexAskSize": null,
    "iexOpen": null,
    "iexOpenTime": null,
    "iexClose": null,
    "iexCloseTime": null,
    "marketCap": 10878525,
    "peRatio": -3.77,
    "week52High": 4.15,
    "week52Low": 0.16,
    "ytdChange": -0.255372,
    "lastTradeTime": 1604597901193
},
{
    "symbol": "ANAV",
    "companyName": "Alpha Network Alliance Ventures, Inc.",
    "primaryExchange": "US OTC",
    "calculationPrice": "close",
    "open": null,
    "openTime": null,
    "openSource": "official",
    "close": null,
    "closeTime": null,
    "closeSource": "official",
    "high": 0.1,
    "highTime": 1606510800000,
    "highSource": "Close",
    "low": 0.0965,
    "lowTime": 1604419834099,
    "lowSource": "15 minute delayed price",
    "latestPrice": 0.0965,
    "latestSource": "Close",
    "latestTime": "November 27, 2020",
    "latestUpdate": 1606510800000,
    "latestVolume": 0,
    "iexRealtimePrice": null,
    "iexRealtimeSize": null,
    "iexLastUpdated": null,
    "delayedPrice": null,
    "delayedPriceTime": null,
    "oddLotDelayedPrice": null,
    "oddLotDelayedPriceTime": null,
    "extendedPrice": 0.089,
    "extendedChange": -0.0075,
    "extendedChangePercent": -0.07772,
    "extendedPriceTime": 0,
    "previousClose": 0.0965,
    "previousVolume": null,
    "change": 0,
    "changePercent": 0,
    "volume": 0,
    "iexMarketPercent": null,
    "iexVolume": null,
    "avgTotalVolume": 67,
    "iexBidPrice": null,
    "iexBidSize": null,
    "iexAskPrice": null,
    "iexAskSize": null,
    "iexOpen": null,
    "iexOpenTime": null,
    "iexClose": null,
    "iexCloseTime": null,
    "marketCap": 10943679,
    "peRatio": -14.62,
    "week52High": 0.1,
    "week52Low": 0.013,
    "ytdChange": 4.744048,
    "lastTradeTime": 1604419834099
},
{
    "symbol": "REVI",
    "companyName": "Resource Ventures, Inc.",
    "primaryExchange": "US OTC",
    "calculationPrice": "close",
    "open": null,
    "openTime": null,
    "openSource": "official",
    "close": null,
    "closeTime": null,
    "closeSource": "official",
    "high": 0.039,
    "highTime": 1585596882000,
    "highSource": "15 minute delayed price",
    "low": 0.0111,
    "lowTime": 1585585122000,
    "lowSource": "15 minute delayed price",
    "latestPrice": 0.0111,
    "latestSource": "Previous close",
    "latestTime": "March 30, 2020",
    "latestUpdate": 1585603200000,
    "latestVolume": 0,
    "iexRealtimePrice": null,
    "iexRealtimeSize": null,
    "iexLastUpdated": null,
    "delayedPrice": null,
    "delayedPriceTime": null,
    "oddLotDelayedPrice": 0.0867,
    "oddLotDelayedPriceTime": 1585596943000,
    "extendedPrice": null,
    "extendedChange": null,
    "extendedChangePercent": null,
    "extendedPriceTime": null,
    "previousClose": null,
    "previousVolume": null,
    "change": null,
    "changePercent": null,
    "volume": 0,
    "iexMarketPercent": null,
    "iexVolume": null,
    "avgTotalVolume": null,
    "iexBidPrice": null,
    "iexBidSize": null,
    "iexAskPrice": null,
    "iexAskSize": null,
    "iexOpen": null,
    "iexOpenTime": null,
    "iexClose": null,
    "iexCloseTime": null,
    "marketCap": 11611,
    "peRatio": null,
    "week52High": 0.0111,
    "week52Low": 0,
    "ytdChange": 0,
    "lastTradeTime": 1585585122000
},
{
    "symbol": "JADG",
    "companyName": "Jade Global Holdings, Inc.",
    "primaryExchange": "US OTC",
    "calculationPrice": "close",
    "open": null,
    "openTime": null,
    "openSource": "official",
    "close": null,
    "closeTime": null,
    "closeSource": "official",
    "high": 0.321,
    "highTime": 1606510800000,
    "highSource": "Close",
    "low": 0.32,
    "lowTime": 1606251600000,
    "lowSource": "Close",
    "latestPrice": 0.321,
    "latestSource": "Close",
    "latestTime": "November 27, 2020",
    "latestUpdate": 1606510800000,
    "latestVolume": 0,
    "iexRealtimePrice": null,
    "iexRealtimeSize": null,
    "iexLastUpdated": null,
    "delayedPrice": null,
    "delayedPriceTime": null,
    "oddLotDelayedPrice": 0.031,
    "oddLotDelayedPriceTime": 1606329768628,
    "extendedPrice": 0,
    "extendedChange": null,
    "extendedChangePercent": null,
    "extendedPriceTime": 0,
    "previousClose": 0.321,
    "previousVolume": 2,
    "change": 0,
    "changePercent": 0,
    "volume": 0,
    "iexMarketPercent": null,
    "iexVolume": null,
    "avgTotalVolume": 83,
    "iexBidPrice": null,
    "iexBidSize": null,
    "iexAskPrice": null,
    "iexAskSize": null,
    "iexOpen": null,
    "iexOpenTime": null,
    "iexClose": null,
    "iexCloseTime": null,
    "marketCap": 3852000,
    "peRatio": -17.93,
    "week52High": 0.62,
    "week52Low": 0.021,
    "ytdChange": 0.993789,
    "lastTradeTime": 1606142484556
},
{
    "symbol": "ADYYF",
    "companyName": "Adyen NV",
    "primaryExchange": "US OTC",
    "calculationPrice": "close",
    "open": 1910,
    "openTime": 1606487846527,
    "openSource": "official",
    "close": 1956.15,
    "closeTime": 1606510800000,
    "closeSource": "official",
    "high": 1956.15,
    "highTime": 1606510800000,
    "highSource": "Close",
    "low": 1910,
    "lowTime": 1606487846527,
    "lowSource": "15 minute delayed price",
    "latestPrice": 1956.15,
    "latestSource": "Close",
    "latestTime": "November 27, 2020",
    "latestUpdate": 1606510800000,
    "latestVolume": 101,
    "iexRealtimePrice": null,
    "iexRealtimeSize": null,
    "iexLastUpdated": null,
    "delayedPrice": 1956.15,
    "delayedPriceTime": 1606499441225,
    "oddLotDelayedPrice": 951.95,
    "oddLotDelayedPriceTime": 1588708175000,
    "extendedPrice": 1850,
    "extendedChange": -106.15,
    "extendedChangePercent": -0.05426,
    "extendedPriceTime": 1606223099601,
    "previousClose": 1823.21,
    "previousVolume": 58,
    "change": 132.94,
    "changePercent": 0.07292,
    "volume": 101,
    "iexMarketPercent": null,
    "iexVolume": null,
    "avgTotalVolume": 1034,
    "iexBidPrice": null,
    "iexBidSize": null,
    "iexAskPrice": null,
    "iexAskSize": null,
    "iexOpen": null,
    "iexOpenTime": null,
    "iexClose": null,
    "iexCloseTime": null,
    "marketCap": 59286211740,
    "peRatio": 278.44,
    "week52High": 2076.16,
    "week52Low": 700,
    "ytdChange": 1.452549,
    "lastTradeTime": 1606499441225
},
{
    "symbol": "NTTIF",
    "companyName": "Novatti Group Ltd.",
    "primaryExchange": "US OTC",
    "calculationPrice": "previousclose",
    "open": null,
    "openTime": null,
    "openSource": "official",
    "close": null,
    "closeTime": null,
    "closeSource": "official",
    "high": null,
    "highTime": null,
    "highSource": null,
    "low": null,
    "lowTime": null,
    "lowSource": null,
    "latestPrice": null,
    "latestSource": "N/A",
    "latestTime": "N/A",
    "latestUpdate": null,
    "latestVolume": 0,
    "iexRealtimePrice": null,
    "iexRealtimeSize": null,
    "iexLastUpdated": null,
    "delayedPrice": null,
    "delayedPriceTime": null,
    "oddLotDelayedPrice": null,
    "oddLotDelayedPriceTime": null,
    "extendedPrice": null,
    "extendedChange": null,
    "extendedChangePercent": null,
    "extendedPriceTime": null,
    "previousClose": null,
    "previousVolume": null,
    "change": null,
    "changePercent": null,
    "volume": 0,
    "iexMarketPercent": null,
    "iexVolume": null,
    "avgTotalVolume": null,
    "iexBidPrice": null,
    "iexBidSize": null,
    "iexAskPrice": null,
    "iexAskSize": null,
    "iexOpen": null,
    "iexOpenTime": null,
    "iexClose": null,
    "iexCloseTime": null,
    "marketCap": null,
    "peRatio": null,
    "week52High": 0,
    "week52Low": 0,
    "ytdChange": 0,
    "lastTradeTime": null
},
{
    "symbol": "NUVCF",
    "companyName": "Nuvei Corp.",
    "primaryExchange": "US OTC",
    "calculationPrice": "close",
    "open": 45,
    "openTime": 1606491127503,
    "openSource": "official",
    "close": 45,
    "closeTime": 1606504800000,
    "closeSource": "official",
    "high": 45,
    "highTime": 1606510800000,
    "highSource": "Close",
    "low": 45,
    "lowTime": 1606491127503,
    "lowSource": "15 minute delayed price",
    "latestPrice": 45,
    "latestSource": "Close",
    "latestTime": "November 27, 2020",
    "latestUpdate": 1606504800000,
    "latestVolume": 103,
    "iexRealtimePrice": null,
    "iexRealtimeSize": null,
    "iexLastUpdated": null,
    "delayedPrice": 45,
    "delayedPriceTime": 1606491127503,
    "oddLotDelayedPrice": 45.883,
    "oddLotDelayedPriceTime": 1606489051869,
    "extendedPrice": null,
    "extendedChange": null,
    "extendedChangePercent": null,
    "extendedPriceTime": null,
    "previousClose": 45,
    "previousVolume": 300,
    "change": 0,
    "changePercent": 0,
    "volume": 103,
    "iexMarketPercent": null,
    "iexVolume": null,
    "avgTotalVolume": 375,
    "iexBidPrice": null,
    "iexBidSize": null,
    "iexAskPrice": null,
    "iexAskSize": null,
    "iexOpen": null,
    "iexOpenTime": null,
    "iexClose": null,
    "iexCloseTime": null,
    "marketCap": 5915691360,
    "peRatio": null,
    "week52High": 45,
    "week52Low": 36.96,
    "ytdChange": 0.165821,
    "lastTradeTime": 1606491127503
},
{
    "symbol": "ICT-H-CV",
    "companyName": "Isee3D, Inc.",
    "primaryExchange": "TSX Venture Exchange",
    "calculationPrice": "close",
    "open": null,
    "openTime": null,
    "openSource": "official",
    "close": null,
    "closeTime": null,
    "closeSource": "official",
    "high": 0.03,
    "highTime": 1574715600000,
    "highSource": null,
    "low": 0.03,
    "lowTime": 1571169600000,
    "lowSource": "Close",
    "latestPrice": 0.03,
    "latestSource": "Close",
    "latestTime": "November 25, 2019",
    "latestUpdate": 1574715600000,
    "latestVolume": 0,
    "iexRealtimePrice": null,
    "iexRealtimeSize": null,
    "iexLastUpdated": null,
    "delayedPrice": null,
    "delayedPriceTime": null,
    "oddLotDelayedPrice": null,
    "oddLotDelayedPriceTime": null,
    "extendedPrice": null,
    "extendedChange": null,
    "extendedChangePercent": null,
    "extendedPriceTime": null,
    "previousClose": 0.03,
    "previousVolume": null,
    "change": 0,
    "changePercent": 0,
    "volume": 0,
    "iexMarketPercent": null,
    "iexVolume": null,
    "avgTotalVolume": 0,
    "iexBidPrice": null,
    "iexBidSize": null,
    "iexAskPrice": null,
    "iexAskSize": null,
    "iexOpen": null,
    "iexOpenTime": null,
    "iexClose": null,
    "iexCloseTime": null,
    "marketCap": 0,
    "peRatio": null,
    "week52High": 0.03,
    "week52Low": 0.03,
    "ytdChange": 0,
    "lastTradeTime": null
},
{
    "symbol": "SPRG-IT",
    "companyName": "Spring Ventures Ltd.",
    "primaryExchange": "Tel Aviv Stock Exchange",
    "calculationPrice": "close",
    "open": null,
    "openTime": null,
    "openSource": "official",
    "close": null,
    "closeTime": null,
    "closeSource": "official",
    "high": 7.51,
    "highTime": 1606510800000,
    "highSource": "Close",
    "low": 7.51,
    "lowTime": 1606510800000,
    "lowSource": "Close",
    "latestPrice": 7.51,
    "latestSource": "Close",
    "latestTime": "November 27, 2020",
    "latestUpdate": 1606510800000,
    "latestVolume": 0,
    "iexRealtimePrice": null,
    "iexRealtimeSize": null,
    "iexLastUpdated": null,
    "delayedPrice": null,
    "delayedPriceTime": null,
    "oddLotDelayedPrice": null,
    "oddLotDelayedPriceTime": null,
    "extendedPrice": null,
    "extendedChange": null,
    "extendedChangePercent": null,
    "extendedPriceTime": null,
    "previousClose": 7.51,
    "previousVolume": null,
    "change": 0,
    "changePercent": 0,
    "volume": 0,
    "iexMarketPercent": null,
    "iexVolume": null,
    "avgTotalVolume": 528,
    "iexBidPrice": null,
    "iexBidSize": null,
    "iexAskPrice": null,
    "iexAskSize": null,
    "iexOpen": null,
    "iexOpenTime": null,
    "iexClose": null,
    "iexCloseTime": null,
    "marketCap": 0,
    "peRatio": null,
    "week52High": 9.28,
    "week52Low": 6.03,
    "ytdChange": 0.197767,
    "lastTradeTime": null
},
{
    "symbol": "HUBWF",
    "companyName": "Proactis SA",
    "primaryExchange": "US OTC",
    "calculationPrice": "previousclose",
    "open": null,
    "openTime": null,
    "close": null,
    "closeTime": null,
    "high": null,
    "low": null,
    "latestPrice": null,
    "latestSource": "N/A",
    "latestTime": "N/A",
    "latestUpdate": null,
    "latestVolume": 0,
    "iexRealtimePrice": null,
    "iexRealtimeSize": null,
    "iexLastUpdated": null,
    "delayedPrice": null,
    "delayedPriceTime": null,
    "extendedPrice": null,
    "extendedChange": null,
    "extendedChangePercent": null,
    "extendedPriceTime": null,
    "previousClose": null,
    "previousVolume": null,
    "change": null,
    "changePercent": null,
    "volume": 0,
    "iexMarketPercent": null,
    "iexVolume": null,
    "avgTotalVolume": null,
    "iexBidPrice": null,
    "iexBidSize": null,
    "iexAskPrice": null,
    "iexAskSize": null,
    "marketCap": null,
    "peRatio": null,
    "week52High": 0,
    "week52Low": 0,
    "ytdChange": 0,
    "lastTradeTime": null
},
{
    "symbol": "DEDAL-FP",
    "companyName": "Dedalus France SA",
    "primaryExchange": "Euronext Paris",
    "calculationPrice": "close",
    "open": null,
    "openTime": null,
    "openSource": "official",
    "close": null,
    "closeTime": null,
    "closeSource": "official",
    "high": 0.8,
    "highTime": 1598299200000,
    "highSource": "Close",
    "low": 0.278,
    "lowTime": 1584561600000,
    "lowSource": "Close",
    "latestPrice": 0.8,
    "latestSource": "Close",
    "latestTime": "August 24, 2020",
    "latestUpdate": 1598299200000,
    "latestVolume": 0,
    "iexRealtimePrice": null,
    "iexRealtimeSize": null,
    "iexLastUpdated": null,
    "delayedPrice": null,
    "delayedPriceTime": null,
    "oddLotDelayedPrice": null,
    "oddLotDelayedPriceTime": null,
    "extendedPrice": null,
    "extendedChange": null,
    "extendedChangePercent": null,
    "extendedPriceTime": null,
    "previousClose": 0.8,
    "previousVolume": null,
    "change": 0,
    "changePercent": 0,
    "volume": 0,
    "iexMarketPercent": null,
    "iexVolume": null,
    "avgTotalVolume": 0,
    "iexBidPrice": null,
    "iexBidSize": null,
    "iexAskPrice": null,
    "iexAskSize": null,
    "iexOpen": null,
    "iexOpenTime": null,
    "iexClose": null,
    "iexCloseTime": null,
    "marketCap": 0,
    "peRatio": null,
    "week52High": 0.99,
    "week52Low": 0.27,
    "ytdChange": 1.051282,
    "lastTradeTime": null
},
{
    "symbol": "BDLN",
    "companyName": "Brilliant Digital Entertainment, Inc.",
    "primaryExchange": "US OTC",
    "calculationPrice": "close",
    "open": null,
    "openTime": null,
    "close": null,
    "closeTime": null,
    "high": null,
    "low": null,
    "latestPrice": 2,
    "latestSource": "Close",
    "latestTime": "August 28, 2015",
    "latestUpdate": 1440792000000,
    "latestVolume": 0,
    "iexRealtimePrice": null,
    "iexRealtimeSize": null,
    "iexLastUpdated": null,
    "delayedPrice": null,
    "delayedPriceTime": null,
    "extendedPrice": null,
    "extendedChange": null,
    "extendedChangePercent": null,
    "extendedPriceTime": null,
    "previousClose": 2,
    "previousVolume": null,
    "change": 0,
    "changePercent": 0,
    "volume": 0,
    "iexMarketPercent": null,
    "iexVolume": null,
    "avgTotalVolume": 0,
    "iexBidPrice": null,
    "iexBidSize": null,
    "iexAskPrice": null,
    "iexAskSize": null,
    "marketCap": 0,
    "peRatio": null,
    "week52High": 2,
    "week52Low": 0,
    "ytdChange": 0,
    "lastTradeTime": null
},
{
    "symbol": "MLRUY",
    "companyName": "Mail.ru Group Ltd.",
    "primaryExchange": "US OTC",
    "calculationPrice": "close",
    "open": null,
    "openTime": null,
    "openSource": "official",
    "close": null,
    "closeTime": null,
    "closeSource": "official",
    "high": 28.13,
    "highTime": 1440792000000,
    "highSource": null,
    "low": 28.13,
    "lowTime": 1437422400000,
    "lowSource": "Close",
    "latestPrice": 28.13,
    "latestSource": "Close",
    "latestTime": "August 28, 2015",
    "latestUpdate": 1440792000000,
    "latestVolume": 0,
    "iexRealtimePrice": null,
    "iexRealtimeSize": null,
    "iexLastUpdated": null,
    "delayedPrice": null,
    "delayedPriceTime": null,
    "oddLotDelayedPrice": null,
    "oddLotDelayedPriceTime": null,
    "extendedPrice": null,
    "extendedChange": null,
    "extendedChangePercent": null,
    "extendedPriceTime": null,
    "previousClose": 28.13,
    "previousVolume": null,
    "change": 0,
    "changePercent": 0,
    "volume": 0,
    "iexMarketPercent": null,
    "iexVolume": null,
    "avgTotalVolume": 0,
    "iexBidPrice": null,
    "iexBidSize": null,
    "iexAskPrice": null,
    "iexAskSize": null,
    "iexOpen": null,
    "iexOpenTime": null,
    "iexClose": null,
    "iexCloseTime": null,
    "marketCap": 5867413967,
    "peRatio": 824.93,
    "week52High": 28.13,
    "week52Low": 0,
    "ytdChange": 0,
    "lastTradeTime": null
},
*/